(()=>{
'use strict';
const ENDPOINT='https://script.google.com/macros/s/AKfycbwNGVkI72M47dpo5wFSzrSTXOz9Uhl_tKH3bg4ntPIXg6w4_y48z6R1xIwAoScX0Bsj2g/exec';
function init(){
 const contact=document.querySelector('#contact'); if(!contact)return;
 let form=document.querySelector('#contactForm');
 if(!form){
  const wrap=document.createElement('div'); wrap.className='portfolio-contact-form';
  wrap.innerHTML=`<form id="contactForm" novalidate><div class="cf-grid"><label><span>Name</span><input name="name" type="text" autocomplete="name" placeholder="Your name" required></label><label><span>Phone</span><input name="phone" type="tel" autocomplete="tel" placeholder="Your phone number" required></label></div><label><span>Email</span><input name="email" type="email" autocomplete="email" placeholder="your@email.com" required></label><label><span>Message</span><textarea name="message" rows="6" placeholder="Write your message..." required></textarea></label><button type="submit"><i class="fa-regular fa-paper-plane"></i><span>Send Message</span></button><p class="cf-status" role="status" aria-live="polite"></p></form>`;
  const target=contact.querySelector('.contact-content')||contact; target.appendChild(wrap); form=wrap.querySelector('form');
 }
 if(form.dataset.contactReady)return; form.dataset.contactReady='1';
 const status=form.querySelector('.cf-status'),button=form.querySelector('[type="submit"]');
 form.addEventListener('submit',async e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const payload={};['name','phone','email','message'].forEach(n=>payload[n]=form.elements[n].value.trim());button.disabled=true;status.textContent='Sending...';status.className='cf-status sending';try{await fetch(ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});form.reset();status.textContent='Message sent successfully!';status.className='cf-status success'}catch(err){status.textContent='Could not send. Please try again.';status.className='cf-status error'}finally{button.disabled=false}});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
const s=document.createElement('style');s.textContent=`.portfolio-contact-form{width:100%;max-width:720px;margin:28px auto 0;text-align:left}.portfolio-contact-form form{display:flex;flex-direction:column;gap:17px;padding:30px;border:1px solid rgba(255,255,255,.11);border-radius:22px;background:linear-gradient(145deg,rgba(13,20,39,.78),rgba(6,12,25,.66));box-shadow:0 25px 70px rgba(0,0,0,.28);backdrop-filter:blur(16px)}.portfolio-contact-form label{display:flex;flex-direction:column;gap:7px}.portfolio-contact-form label span{font:700 11px 'Manrope',sans-serif;color:#aebbd0;letter-spacing:.5px}.portfolio-contact-form input,.portfolio-contact-form textarea{width:100%;border:1px solid rgba(255,255,255,.11);border-radius:13px;background:rgba(255,255,255,.035);color:#f4f8ff;padding:13px 15px;outline:none;font:500 14px 'Manrope',sans-serif;transition:.22s;resize:vertical}.portfolio-contact-form input::placeholder,.portfolio-contact-form textarea::placeholder{color:#68778b}.portfolio-contact-form input:focus,.portfolio-contact-form textarea:focus{border-color:rgba(87,230,255,.55);box-shadow:0 0 0 3px rgba(87,230,255,.07)}.cf-grid{display:grid;grid-template-columns:1fr 1fr;gap:17px}.portfolio-contact-form button{align-self:flex-start;border:0;border-radius:13px;padding:13px 22px;background:linear-gradient(135deg,#78bcff,#4d8ff0 55%,#6d75ff);color:#fff;font:800 14px 'Manrope',sans-serif;cursor:pointer;box-shadow:0 12px 35px rgba(76,145,239,.22);transition:.22s}.portfolio-contact-form button:hover:not(:disabled){transform:translateY(-2px);box-shadow:0 17px 40px rgba(76,145,239,.3)}.portfolio-contact-form button:disabled{opacity:.65;cursor:wait}.cf-status{min-height:20px;margin:0;font:600 12px 'Manrope',sans-serif}.cf-status.sending{color:#8ebfff}.cf-status.success{color:#5ff0ae}.cf-status.error{color:#ff7f8b}@media(max-width:600px){.portfolio-contact-form form{padding:21px}.cf-grid{grid-template-columns:1fr}.portfolio-contact-form button{width:100%}}`;document.head.appendChild(s);
})();
