(()=>{
'use strict';
const ENDPOINT='https://script.google.com/macros/s/AKfycbwNGVkI72M47dpo5wFSzrSTXOz9Uhl_tKH3bg4ntPIXg6w4_y48z6R1xIwAoScX0Bsj2g/exec';
function init(){
 const contact=document.querySelector('#contact');if(!contact)return;
 let form=document.querySelector('#contactForm');
 if(!form){const wrap=document.createElement('div');wrap.className='portfolio-contact-form';wrap.innerHTML=`<form id="contactForm" novalidate><div class="cf-grid"><label><span data-en="Name" data-bn="নাম">Name</span><input name="name" type="text" required autocomplete="name" placeholder="Your name" data-placeholder-en="Your name" data-placeholder-bn="আপনার নাম"></label><label><span data-en="Phone" data-bn="ফোন">Phone</span><input name="phone" type="tel" required autocomplete="tel" placeholder="Your phone number" data-placeholder-en="Your phone number" data-placeholder-bn="আপনার ফোন নম্বর"></label></div><label><span data-en="Email" data-bn="ইমেইল">Email</span><input name="email" type="email" required autocomplete="email" placeholder="you@example.com" data-placeholder-en="you@example.com" data-placeholder-bn="আপনার ইমেইল"></label><label><span data-en="Message" data-bn="মেসেজ">Message</span><textarea name="message" rows="6" required placeholder="Write your message..." data-placeholder-en="Write your message..." data-placeholder-bn="আপনার মেসেজ লিখুন..."></textarea></label><button type="submit"><i class="fa-solid fa-paper-plane"></i><span data-en="Send Message" data-bn="মেসেজ পাঠান">Send Message</span></button><p class="cf-status" role="status" aria-live="polite"></p></form>`;(contact.querySelector('.contact-content')||contact).appendChild(wrap);form=wrap.querySelector('form');}
 if(form.dataset.contactReady)return;form.dataset.contactReady='1';
 const status=form.querySelector('.cf-status'),button=form.querySelector('[type="submit"]');
 const sync=()=>{const bn=document.documentElement.lang==='bn';form.querySelectorAll('[data-placeholder-en]').forEach(x=>x.placeholder=bn?x.dataset.placeholderBn:x.dataset.placeholderEn)};sync();
 new MutationObserver(sync).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
 form.addEventListener('submit',async e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const original=button.innerHTML;button.disabled=true;button.classList.add('is-sending');button.innerHTML='<i class="fa-solid fa-circle-notch fa-spin"></i> <span data-en="Sending..." data-bn="পাঠানো হচ্ছে...">Sending...</span>';status.textContent='';const payload={name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),email:form.elements.email.value.trim(),message:form.elements.message.value.trim()};try{await fetch(ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});form.reset();status.textContent=document.documentElement.lang==='bn'?'মেসেজ সফলভাবে পাঠানো হয়েছে।':'Message sent successfully.';status.className='cf-status success';showSuccess()}catch(err){status.textContent=document.documentElement.lang==='bn'?'মেসেজ পাঠানো যায়নি। আবার চেষ্টা করুন।':'Could not send the message. Please try again.';status.className='cf-status error'}finally{button.disabled=false;button.classList.remove('is-sending');button.innerHTML=original}});
 function showSuccess(){let old=document.querySelector('.cf-toast');if(old)old.remove();const t=document.createElement('div');t.className='cf-toast';t.innerHTML='<i class="fa-solid fa-circle-check"></i><div><strong>'+(document.documentElement.lang==='bn'?'মেসেজ পাঠানো হয়েছে!':'Message sent!')+'</strong><small>'+(document.documentElement.lang==='bn'?'আপনার মেসেজ সফলভাবে পৌঁছে গেছে।':'Your message has been sent successfully.')+'</small></div>';document.body.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>{t.classList.remove('show');setTimeout(()=>t.remove(),350)},4200)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
const s=document.createElement('style');s.textContent=`.portfolio-contact-form{width:100%;max-width:720px;margin:28px auto 0}.portfolio-contact-form form{display:flex;flex-direction:column;gap:17px;padding:30px;border:1px solid rgba(255,255,255,.11);border-radius:22px;background:linear-gradient(145deg,rgba(13,20,39,.78),rgba(6,12,25,.66));box-shadow:0 25px 70px rgba(0,0,0,.28);backdrop-filter:blur(16px);text-align:left}.portfolio-contact-form label{display:flex;flex-direction:column;gap:7px}.portfolio-contact-form label span{font:700 11px 'Manrope',sans-serif;color:#aebbd0;letter-spacing:.5px}.portfolio-contact-form input,.portfolio-contact-form textarea{width:100%;border:1px solid rgba(255,255,255,.11);border-radius:13px;background:rgba(255,255,255,.035);color:#f4f8ff;padding:13px 15px;outline:none;font:500 14px 'Manrope',sans-serif;transition:.22s;resize:vertical}.portfolio-contact-form input:focus,.portfolio-contact-form textarea:focus{border-color:rgba(87,230,255,.55);box-shadow:0 0 0 3px rgba(87,230,255,.07)}.cf-grid{display:grid;grid-template-columns:1fr 1fr;gap:17px}.portfolio-contact-form button{align-self:flex-start;border:0;border-radius:13px;padding:13px 22px;background:linear-gradient(135deg,#78bcff,#4d8ff0 55%,#6d75ff);color:#fff;font:800 14px 'Manrope',sans-serif;cursor:pointer;box-shadow:0 12px 35px rgba(76,145,239,.22);transition:.22s}.portfolio-contact-form button:hover:not(:disabled){transform:translateY(-2px);box-shadow:0 17px 40px rgba(76,145,239,.3)}.portfolio-contact-form button.is-sending{transform:scale(.98);opacity:.8}.portfolio-contact-form button:disabled{cursor:wait}.cf-status{min-height:20px;margin:0;font:600 12px 'Manrope',sans-serif}.cf-status.success{color:#5ff0ae}.cf-status.error{color:#ff7f8b}.cf-toast{position:fixed;right:24px;bottom:24px;z-index:9999;display:flex;align-items:center;gap:13px;min-width:290px;padding:15px 18px;border:1px solid rgba(95,240,174,.25);border-radius:15px;background:rgba(7,16,25,.94);box-shadow:0 18px 55px rgba(0,0,0,.35);backdrop-filter:blur(15px);color:#eef7f2;transform:translateY(20px);opacity:0;transition:.35s}.cf-toast.show{transform:translateY(0);opacity:1}.cf-toast>i{font-size:23px;color:#5ff0ae}.cf-toast strong,.cf-toast small{display:block}.cf-toast strong{font:800 13px 'Manrope',sans-serif}.cf-toast small{margin-top:2px;color:#91a4a1;font:500 10px 'Manrope',sans-serif}@media(max-width:600px){.portfolio-contact-form form{padding:21px}.cf-grid{grid-template-columns:1fr}.portfolio-contact-form button{width:100%}.cf-toast{left:16px;right:16px;bottom:16px;min-width:0}}`;document.head.appendChild(s);
})();
