(()=>{
'use strict';
const d=document.documentElement,b=document.body;
const L=localStorage.getItem('portfolio-lang')||localStorage.getItem('portfolio-language')||'en';
const T=localStorage.getItem('portfolio-theme')||'dark';
function lang(x){d.lang=x;document.querySelectorAll('[data-en][data-bn]').forEach(e=>e.textContent=e.dataset[x==='bn'?'bn':'en']);localStorage.setItem('portfolio-lang',x);localStorage.setItem('portfolio-language',x)}
lang(L);
function theme(x){b.classList.remove('light','theme-purple','theme-amber','theme-cyan');if(x==='light')b.classList.add('light');else if(x!=='dark')b.classList.add(x);localStorage.setItem('portfolio-theme',x)}
theme(T);
const style=document.createElement('style');style.textContent=`.project-image.live-preview{position:relative!important;height:220px!important;min-height:220px!important;overflow:hidden!important;background:#071018!important;border:1px solid rgba(67,245,160,.12)!important;border-radius:14px}.project-image.live-preview:before{content:'PROJECT PREVIEW';position:absolute;z-index:3;top:10px;left:10px;padding:5px 8px;border:1px solid rgba(67,245,160,.28);border-radius:6px;background:rgba(2,8,12,.78);color:var(--neon,#43f5a0);font:700 8px monospace;letter-spacing:1px}.project-image.live-preview img{display:block;width:100%;height:100%;object-fit:cover;object-position:top center}.project-image.live-preview .preview-loader{position:absolute;inset:0;z-index:1;display:flex;align-items:center;justify-content:center;color:#7890a0;background:#071018;font:600 9px monospace;letter-spacing:1px}.project-image.live-preview.loaded .preview-loader{display:none}@media(max-width:680px){.project-image.live-preview{height:190px!important;min-height:190px!important}}`;document.head.appendChild(style);
// Generate previews directly from each project's URL.
d.querySelectorAll('#projects .project-card').forEach(card=>{const link=card.querySelector('.project-link'),image=card.querySelector('.project-image');if(!link||!image)return;image.className='project-image live-preview';image.innerHTML='<div class="preview-loader">LOADING PREVIEW...</div>';const img=document.createElement('img');img.src='https://image.thum.io/get/width/1200/crop/700/noanimate/'+encodeURIComponent(link.href);img.alt=(card.querySelector('h3')?.textContent||'Project')+' preview';img.loading='lazy';img.onload=()=>image.classList.add('loaded');img.onerror=()=>{const loader=image.querySelector('.preview-loader');if(loader)loader.textContent='PREVIEW UNAVAILABLE'};image.appendChild(img)});
})();