(()=>{
const d=document.documentElement,b=document.body;
const L=localStorage.getItem('portfolio-lang')||'en',T=localStorage.getItem('portfolio-theme')||'dark';
d.lang=L;b.classList.toggle('light',T==='light');if(T!=='dark'&&T!=='light')b.classList.add(T);
function lang(x){d.lang=x;document.querySelectorAll('[data-en][data-bn]').forEach(e=>e.textContent=e.dataset[x==='bn'?'bn':'en']);localStorage.setItem('portfolio-lang',x);document.querySelectorAll('.language-toggle span[data-lang]').forEach(e=>e.classList.toggle('active',e.dataset.lang===x))}lang(L);
d.getElementById('languageToggle')?.addEventListener('click',()=>lang(d.lang==='bn'?'en':'bn'));
function theme(x){b.classList.remove('light','theme-purple','theme-amber','theme-cyan');if(x==='light')b.classList.add('light');else if(x!=='dark')b.classList.add(x);localStorage.setItem('portfolio-theme',x);const q=document.getElementById('themeLabel');if(q)q.textContent=x==='dark'?'DARK':x==='light'?'LIGHT':x.replace('theme-','').toUpperCase();document.getElementById('themeMenu')?.classList.remove('open')}theme(T);
d.getElementById('themeButton')?.addEventListener('click',e=>{e.stopPropagation();document.getElementById('themeMenu')?.classList.toggle('open')});document.querySelectorAll('.theme-choice').forEach(x=>x.onclick=()=>theme(x.dataset.theme));
d.getElementById('mobileMenuButton')?.addEventListener('click',e=>{e.stopPropagation();document.getElementById('mobileMenu')?.classList.toggle('open')});document.querySelectorAll('#mobileMenu a').forEach(x=>x.onclick=()=>document.getElementById('mobileMenu')?.classList.remove('open'));
const boot=document.getElementById('boot-screen');if(boot)setTimeout(()=>boot.classList.add('loaded'),2300);
const c=document.createElement('canvas');c.style='position:fixed;inset:0;z-index:-2;pointer-events:none;opacity:.08';document.body.prepend(c);const x=c.getContext('2d');let w,h,a;function r(){w=c.width=innerWidth;h=c.height=innerHeight;a=Array(Math.floor(w/18)).fill(1)}function m(){x.clearRect(0,0,w,h);x.fillStyle=getComputedStyle(b).getPropertyValue('--neon')||'#43f5a0';x.font='11px monospace';a.forEach((v,i)=>{x.fillText(Math.random()>.5?'0':'1',i*18,v*18);if(v*18>h&&Math.random()>.975)a[i]=0;a[i]++});requestAnimationFrame(m)}r();addEventListener('resize',r);m();
})();