// PORTFOLIO INTERACTIONS - PERFORMANCE OPTIMIZED
console.log("Mahmudul Arefin Rafi's Portfolio Loaded Successfully!");

const bootScreen=document.getElementById("boot-screen");
const revealBoot=()=>bootScreen&&bootScreen.classList.add("loaded");
if(bootScreen){window.addEventListener("load",()=>setTimeout(revealBoot,250),{once:true});setTimeout(revealBoot,900)}

// Language
const languageToggle=document.getElementById("languageToggle");
const translatableElements=document.querySelectorAll("[data-en][data-bn]");
function setLanguage(language){const bn=language==="bn";document.documentElement.lang=bn?"bn":"en";document.body.classList.toggle("bn-mode",bn);translatableElements.forEach(el=>el.textContent=bn?el.dataset.bn:el.dataset.en);if(languageToggle){languageToggle.querySelectorAll("span").forEach(s=>s.classList.remove("active"));const active=languageToggle.querySelector(bn?"span:last-of-type":"span:first-of-type");if(active)active.classList.add("active")}localStorage.setItem("portfolioLanguage",language)}
setLanguage(localStorage.getItem("portfolioLanguage")||"en");
if(languageToggle)languageToggle.addEventListener("click",()=>setLanguage(document.body.classList.contains("bn-mode")?"en":"bn"));

// Theme
const themeButton=document.getElementById("themeButton"),themeMenu=document.getElementById("themeMenu"),themeLabel=document.getElementById("themeLabel"),themeChoices=document.querySelectorAll(".theme-choice");
const themeNames={dark:"DARK",light:"LIGHT","theme-purple":"PURPLE","theme-cyan":"CYAN","theme-amber":"AMBER"};
function setTheme(theme){document.body.classList.remove("light","theme-purple","theme-cyan","theme-amber");if(theme!=="dark")document.body.classList.add(theme);if(themeLabel)themeLabel.textContent=themeNames[theme]||"DARK";localStorage.setItem("portfolioTheme",theme)}
setTheme(localStorage.getItem("portfolioTheme")||"dark");
if(themeButton&&themeMenu){themeButton.addEventListener("click",e=>{e.stopPropagation();themeMenu.classList.toggle("open")});themeChoices.forEach(c=>c.addEventListener("click",()=>{setTheme(c.dataset.theme||"dark");themeMenu.classList.remove("open")}));document.addEventListener("click",()=>themeMenu.classList.remove("open"))}

// Mobile menu and smooth scrolling
const mobileMenuButton=document.getElementById("mobileMenuButton"),mobileMenu=document.getElementById("mobileMenu");
if(mobileMenuButton&&mobileMenu){mobileMenuButton.addEventListener("click",e=>{e.stopPropagation();mobileMenu.classList.toggle("open")});mobileMenu.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>mobileMenu.classList.remove("open")))}
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener("click",function(e){const id=this.getAttribute("href"),target=document.querySelector(id);if(target){e.preventDefault();target.scrollIntoView({behavior:"smooth",block:"start"})}}));

// Professional status strip
const hero=document.querySelector("#home.hero");
if(hero&&!document.querySelector(".professional-strip")){const strip=document.createElement("div");strip.className="professional-strip";strip.innerHTML=`<div class="pro-title"></div><div class="pro-grid"><div class="pro-card"><span class="pro-label" data-en="Current Focus" data-bn="বর্তমান ফোকাস">Current Focus</span><div class="pro-value" data-en="Software & Web Development" data-bn="সফটওয়্যার ও ওয়েব ডেভেলপমেন্ট">Software & Web Development</div></div><div class="pro-card"><span class="pro-label" data-en="Education" data-bn="শিক্ষা">Education</span><div class="pro-value" data-en="CSE • Uttara University" data-bn="CSE • উত্তরা বিশ্ববিদ্যালয়">CSE • Uttara University</div></div><div class="pro-card"><span class="pro-label" data-en="Professional Focus" data-bn="পেশাগত ফোকাস">Professional Focus</span><div class="pro-value" data-en="Technology • Digital Marketing" data-bn="প্রযুক্তি • ডিজিটাল মার্কেটিং">Technology • Digital Marketing</div></div><div class="pro-card"><span class="pro-label" data-en="Status" data-bn="স্ট্যাটাস">Status</span><div class="pro-value"><span class="online" data-en="Open to Opportunities" data-bn="নতুন সুযোগের জন্য আগ্রহী">Open to Opportunities</span></div></div></div>`;hero.insertAdjacentElement("afterend",strip)}

// Website preview images
(()=>{const style=document.createElement('style');style.textContent=`.project-image.website-preview{position:relative!important;overflow:hidden!important;height:230px!important;min-height:230px!important;background:#0a1018!important;border:1px solid rgba(67,245,160,.12)!important;border-radius:12px}.project-image.website-preview>span{display:none!important}.project-image.website-preview .preview-label{position:absolute;top:9px;left:9px;z-index:4;padding:4px 7px;border:1px solid rgba(67,245,160,.28);border-radius:5px;background:rgba(2,8,12,.82);color:var(--neon,#43f5a0);font:700 8px monospace;letter-spacing:1px}.project-image.website-preview img{display:block;width:100%;height:100%;object-fit:cover;object-position:top center;background:#fff;transition:transform .45s ease,filter .3s ease}.project-image.website-preview:after{content:'';position:absolute;inset:0;z-index:2;pointer-events:none;background:linear-gradient(180deg,transparent 55%,rgba(0,0,0,.18))}.project-card:hover .project-image.website-preview img{transform:scale(1.03)}@media(max-width:680px){.project-image.website-preview{height:190px!important;min-height:190px!important}}`;document.head.appendChild(style);document.querySelectorAll('#projects .project-card').forEach(card=>{const link=card.querySelector('.project-link'),image=card.querySelector('.project-image');if(!link||!image)return;image.classList.add('website-preview');const label=document.createElement('div');label.className='preview-label';label.textContent='PROJECT PREVIEW';image.appendChild(label);const img=document.createElement('img');img.alt=(card.querySelector('h3')?.textContent||'Project')+' website preview';img.loading='lazy';img.src='https://image.thum.io/get/width/1200/crop/700/noanimate/'+link.href;image.appendChild(img)})})();

// PROJECT SHOWCASE: exactly the existing 20 cards, unchanged order, no injected duplicates.
(()=>{const grid=document.querySelector('#projects .projects-container');if(!grid)return;const cards=[...grid.querySelectorAll('.project-card')];if(cards.length!==20)return;
// Base category for each existing card in the original order. Featured is a separate flag.
const categories=['utility','web','education','app','web','education','utility','app','app','education','app','app','education','app','utility','app','utility','web','web','utility'];
cards.forEach((card,i)=>{card.dataset.category=categories[i]||'web';card.dataset.featured=i<5?'true':'false';if(i<5)card.classList.add('featured-project')});
const filters=[['all','All Projects'],['featured','Featured'],['web','Web'],['app','Apps'],['utility','Utility'],['education','Education']];
const style=document.createElement('style');style.textContent=`#projects .project-filters{display:flex;flex-wrap:wrap;gap:8px;margin:0 auto 28px;justify-content:center}#projects .project-filter{border:1px solid rgba(67,245,160,.16);background:rgba(255,255,255,.025);color:#91a0ad;border-radius:999px;padding:9px 14px;font:700 10px 'JetBrains Mono',monospace;cursor:pointer;transition:transform .2s,background .2s,border-color .2s,color .2s}.project-filter:hover{transform:translateY(-2px)}#projects .project-filter:hover,#projects .project-filter.active{color:var(--neon,#43f5a0);border-color:rgba(67,245,160,.48);background:rgba(67,245,160,.07)}#projects .project-card.filtered-out{display:none!important}#projects .project-card.featured-project{border-color:rgba(67,245,160,.22);box-shadow:0 12px 35px rgba(0,0,0,.12)}#projects .project-card.featured-project:before{content:'FEATURED';position:absolute;right:14px;top:14px;z-index:8;padding:4px 7px;border:1px solid rgba(67,245,160,.3);border-radius:5px;background:rgba(2,8,12,.82);color:var(--neon,#43f5a0);font:700 7px 'JetBrains Mono',monospace;letter-spacing:1px}@media(max-width:680px){#projects .project-filters{justify-content:flex-start;overflow-x:auto;flex-wrap:nowrap;padding:0 2px 8px;scrollbar-width:none;-webkit-overflow-scrolling:touch}#projects .project-filters::-webkit-scrollbar{display:none}#projects .project-filter{flex:0 0 auto}}`;document.head.appendChild(style);
const filterBar=document.createElement('div');filterBar.className='project-filters';filters.forEach(([key,label],i)=>{const b=document.createElement('button');b.type='button';b.className='project-filter'+(i===0?' active':'');b.dataset.filter=key;b.textContent=label;filterBar.appendChild(b)});const sub=document.querySelector('#projects .projects-subtitle');if(sub)sub.insertAdjacentElement('afterend',filterBar);else grid.insertAdjacentElement('beforebegin',filterBar);
filterBar.addEventListener('click',e=>{const button=e.target.closest('.project-filter');if(!button)return;filterBar.querySelectorAll('.project-filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');const selected=button.dataset.filter;cards.forEach(card=>{const show=selected==='all'||(selected==='featured'&&card.dataset.featured==='true')||card.dataset.category===selected;card.classList.toggle('filtered-out',!show)})});
})();

// Lightweight desktop cursor
if(window.matchMedia("(pointer:fine)").matches){const bubble=document.querySelector(".cursor-bubble")||document.createElement("div"),dot=document.querySelector(".cursor-dot")||document.createElement("div");bubble.className="cursor-bubble";dot.className="cursor-dot";if(!bubble.parentElement)document.body.appendChild(bubble);if(!dot.parentElement)document.body.appendChild(dot);let mx=innerWidth/2,my=innerHeight/2,bx=mx,by=my;function tick(){bx+=(mx-bx)*.18;by+=(my-by)*.18;bubble.style.transform=`translate3d(${bx}px,${by}px,0) translate(-50%,-50%)`;dot.style.transform=`translate3d(${mx}px,${my}px,0) translate(-50%,-50%)`;requestAnimationFrame(tick)}tick();addEventListener("mousemove",e=>{mx=e.clientX;my=e.clientY;bubble.style.opacity=1;dot.style.opacity=1},{passive:true});document.querySelectorAll("a,button,.skill-card,.project-card,.pro-card").forEach(el=>{el.addEventListener("mouseenter",()=>bubble.classList.add("hovering"));el.addEventListener("mouseleave",()=>bubble.classList.remove("hovering"))})}
