(()=>{
'use strict';
const cursorScript=document.createElement('script');cursorScript.src='cursor-effects.js?v=2';cursorScript.defer=true;document.head.appendChild(cursorScript);
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();
const langBtn=document.getElementById('languageToggle'),themeBtn=document.getElementById('themeButton');
function setLanguage(lang){document.querySelectorAll('[data-en][data-bn]').forEach(el=>el.textContent=lang==='bn'?el.dataset.bn:el.dataset.en);document.documentElement.lang=lang==='bn'?'bn':'en';if(langBtn)langBtn.textContent=lang==='bn'?'বাংলা / EN':'EN / বাংলা';localStorage.setItem('portfolio-language',lang);localStorage.setItem('portfolio-lang',lang)}
setLanguage(localStorage.getItem('portfolio-language')||localStorage.getItem('portfolio-lang')||'en');
if(langBtn)langBtn.addEventListener('click',()=>setLanguage((localStorage.getItem('portfolio-language')||localStorage.getItem('portfolio-lang')||'en')==='en'?'bn':'en'));
const themes=['dark','purple','cyan','amber','midnight'];let theme=localStorage.getItem('portfolio-theme')||'dark';
function setTheme(t){theme=t;document.body.classList.remove('light','theme-purple','theme-cyan','theme-amber','theme-midnight');if(t!=='dark')document.body.classList.add('theme-'+t);if(themeBtn)themeBtn.textContent=t==='dark'?'DARK':t.toUpperCase();localStorage.setItem('portfolio-theme',t)}
setTheme(theme);if(themeBtn)themeBtn.addEventListener('click',()=>{const i=themes.indexOf(theme);setTheme(themes[(i+1)%themes.length])});
const navLinks=document.querySelector('.nav-links'),menuBtn=document.getElementById('mobileMenuButton');if(navLinks&&menuBtn){menuBtn.addEventListener('click',()=>navLinks.classList.toggle('show'));navLinks.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('show')))}
const fa=document.createElement('link');fa.rel='stylesheet';fa.href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css';fa.crossOrigin='anonymous';document.head.appendChild(fa);
const iconStyle=document.createElement('style');iconStyle.textContent=`.nav-links a::before,.btn::before,.skill-card h3::before,.education-card h4::before,.project-link::before{font-family:'Font Awesome 6 Free';font-weight:900;display:inline-block;margin-right:8px;opacity:.9}.nav-links a[href='#home']::before{content:'\\f015'}.nav-links a[href='#about']::before{content:'\\f007'}.nav-links a[href='#skills']::before{content:'\\f085'}.nav-links a[href='#education']::before{content:'\\f19d'}.nav-links a[href='#projects']::before{content:'\\f1b2'}.nav-links a[href='#contact']::before{content:'\\f0e0'}.btn[href='#projects']::before{content:'\\f1b2'}.btn[href='#contact']::before{content:'\\f0e0'}.skill-card:nth-child(1) h3::before{content:'\\f121'}.skill-card:nth-child(2) h3::before{content:'\\f0ac'}.skill-card:nth-child(3) h3::before{content:'\\f201'}.skill-card:nth-child(4) h3::before{content:'\\f508'}.education-card h4::before{content:'\\f19d'}.project-link::before{content:'\\f35d'}`;document.head.appendChild(iconStyle);
const contact=document.querySelector('#contact');
if(contact&&!contact.querySelector('#contactForm')){const box=document.createElement('div');box.className='contact-form-wrap';box.innerHTML=`<form id="contactForm" class="contact-form" novalidate><div class="contact-form-grid"><label><span data-en="Name" data-bn="নাম">Name</span><input name="name" type="text" required autocomplete="name" placeholder="Your name" data-placeholder-en="Your name" data-placeholder-bn="আপনার নাম"></label><label><span data-en="Phone" data-bn="ফোন">Phone</span><input name="phone" type="tel" required autocomplete="tel" placeholder="Your phone" data-placeholder-en="Your phone" data-placeholder-bn="আপনার ফোন"></label><label><span data-en="Email" data-bn="ইমেইল">Email</span><input name="email" type="email" required autocomplete="email" placeholder="you@example.com" data-placeholder-en="you@example.com" data-placeholder-bn="আপনার ইমেইল"></label></div><label class="contact-message"><span data-en="Message" data-bn="মেসেজ">Message</span><textarea name="message" rows="6" required placeholder="Write your message..." data-placeholder-en="Write your message..." data-placeholder-bn="আপনার মেসেজ লিখুন..."></textarea></label><button type="submit" class="btn"><i class="fa-solid fa-paper-plane"></i> <span data-en="Send Message" data-bn="মেসেজ পাঠান">Send Message</span></button><p class="contact-status" aria-live="polite"></p></form>`;contact.appendChild(box);const form=box.querySelector('#contactForm'),status=box.querySelector('.contact-status');form.addEventListener('submit',async e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const button=form.querySelector('[type="submit"]'),original=button.innerHTML;button.disabled=true;button.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Sending...';status.textContent='';const payload={name:form.name.value.trim(),phone:form.phone.value.trim(),email:form.email.value.trim(),message:form.message.value.trim()};try{await fetch('https://script.google.com/macros/s/AKfycbwNGVkI72M47dpo5wFSzrSTXOz9Uhl_tKH3bg4ntPIXg6w4_y48z6R1xIwAoScX0Bsj2g/exec',{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});form.reset();status.textContent=document.documentElement.lang==='bn'?'মেসেজ সফলভাবে পাঠানো হয়েছে।':'Message sent successfully.'}catch(err){status.textContent=document.documentElement.lang==='bn'?'মেসেজ পাঠানো যায়নি। আবার চেষ্টা করুন।':'Could not send the message. Please try again.'}finally{button.disabled=false;button.innerHTML=original}})}
const motionStyle=document.createElement('style');motionStyle.textContent=`html{scroll-behavior:smooth}section{scroll-margin-top:90px}.reveal,.reveal-left,.reveal-right{opacity:0;transition:opacity .8s ease,transform .8s cubic-bezier(.2,.75,.2,1)}.reveal{transform:translateY(30px)}.reveal-left{transform:translateX(-34px)}.reveal-right{transform:translateX(34px)}.reveal.revealed,.reveal-left.revealed,.reveal-right.revealed{opacity:1;transform:none}.hero h1,.hero h2,.section-title h2{background:linear-gradient(110deg,#fff 8%,#bcd8ff 42%,#3a86ff 70%,#9b7cff 100%);background-size:220% auto;-webkit-background-clip:text;background-clip:text;color:transparent;animation:rafiGradient 8s ease-in-out infinite alternate}@keyframes rafiGradient{from{background-position:0 center}to{background-position:100% center}}.hero-image{animation:rafiFloat 6s ease-in-out infinite}.hero-image img{transition:transform .45s ease,filter .45s ease}.hero-image:hover img{transform:translateY(-5px) scale(1.025);filter:saturate(1.08)}@keyframes rafiFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-9px)}}.btn{position:relative;overflow:hidden;transition:transform .25s ease,box-shadow .25s ease}.btn:after{content:'';position:absolute;top:-20%;bottom:-20%;left:-70%;width:45%;transform:skewX(-18deg);background:linear-gradient(90deg,transparent,rgba(255,255,255,.3),transparent);transition:left .65s ease;pointer-events:none}.btn:hover:after{left:125%}.btn:hover{transform:translateY(-3px);box-shadow:0 14px 34px rgba(58,134,255,.22)}.project-card,.skill-card,.education-card,.about-content,.pro-card{transition:transform .35s cubic-bezier(.2,.8,.2,1),box-shadow .35s,border-color .35s}.project-card:hover,.skill-card:hover,.education-card:hover,.about-content:hover{transform:translateY(-7px);box-shadow:0 20px 55px rgba(0,0,0,.25);border-color:rgba(58,134,255,.35)}.project-card,.skill-card,.education-card,.about-content,.pro-card{background:linear-gradient(135deg,rgba(255,255,255,.055),rgba(255,255,255,.018));backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px)}@media(max-width:680px){.hero h1,.hero h2{animation:none}.hero-image{animation-duration:7s}.project-card:hover,.skill-card:hover,.education-card:hover,.about-content:hover{transform:translateY(-4px)}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal,.reveal-left,.reveal-right{opacity:1!important;transform:none!important;transition:none!important}.hero-image,.hero h1,.hero h2,.section-title h2{animation:none!important}.btn,.project-card,.skill-card,.education-card,.about-content{transition:none!important}}`;document.head.appendChild(motionStyle);
const revealTargets=[...document.querySelectorAll('section:not(#home),.project-card,.skill-card,.education-card,.about-content,.pro-card')];revealTargets.forEach((el,i)=>{if(!el.classList.contains('reveal')&&!el.classList.contains('revealed'))el.classList.add(i%3===1?'reveal-left':i%3===2?'reveal-right':'reveal')});if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -40px 0px'});revealTargets.forEach(el=>observer.observe(el))}else revealTargets.forEach(el=>el.classList.add('revealed'));
const hero=document.querySelector('.hero'),heroText=document.querySelector('.hero-text'),heroImage=document.querySelector('.hero-image');if(hero&&heroText&&heroImage&&window.matchMedia('(prefers-reduced-motion: no-preference)').matches){hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;heroText.style.transform=`translate3d(${x*-8}px,${y*-6}px,0)`;heroImage.style.transform=`translate3d(${x*10}px,${y*8}px,0)`});hero.addEventListener('pointerleave',()=>{heroText.style.transform='';heroImage.style.transform=''})}
})();